version: '3.8'

services:
  api:
    build: 
      context: ./api
    env_file:
      - .env
    environment:
      - IMAGE=${API_NAME}:${TAG}
      - HOST=${HOST}
      - PORT=${PORT}
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - SERVER_RELOAD=${SERVER_RELOAD}
      - DEPLOYMENT_CMD=${DEPLOYMENT_CMD}
    volumes:
      - ./api/app:/app
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks: 
      - frontend
      - backend
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge  
