version: '3.8'

services:
  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - IMAGE=${NAME}:${TAG}
    volumes:
      - ./app/:/app
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks: 
      - frontend
      - backend

volumes:
  app: 
    driver: local
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge  
