version: '3.8'

services:
  api:
    build: 
      context: ./api
    volumes:
      - ./api/app:/app
    ports:
      - 80:80
    restart: always
    networks: 
      - frontend
      - backend
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge  
